#!/bin/bash

# 🚀 SmartLandLedger - QUICK REFERENCE
# =====================================

echo "🎉 SmartLandLedger - Blockchain Land Registration"
echo "=================================================="
echo ""
echo "📚 DOCUMENTATION:"
echo "  1. README.md                → Project overview"
echo "  2. QUICKSTART.md            → How to run (5 min setup)"
echo "  3. DEMONSTRATION_GUIDE.md   → How to demonstrate the system"
echo "  4. DASHBOARD_GUIDE.md       → Dashboard user guide"
echo ""
echo "🚀 QUICK START:"
echo ""
echo "   # Terminal 1: Start blockchain"
echo "   npm run hardhat:node"
echo ""
echo "   # Terminal 2: Deploy contracts"
echo "   npm run hardhat:deploy"
echo ""
echo "   # Terminal 3: Start frontend (from app folder)"
echo "   cd app && npm run dev"
echo ""
echo "   Then open: http://localhost:3000"
echo ""
echo "========================================"
echo "✅ STACK: Hardhat | Next.js | Ethers.js"
echo "✅ SOLIDITY: 0.8.19"
echo "✅ STATUS: Ready to Deploy"
echo "========================================"
