#!/bin/bash

# 🚀 LAND REGISTRATION SYSTEM - QUICK REFERENCE
# ================================================

echo "🎉 Land Registration System - Modernized Stack"
echo "=============================================="
echo ""
echo "📍 LOCATION: /Users/indusahu/playground/Land-Registration-with-Blockchain"
echo ""
echo "📚 DOCUMENTATION:"
echo "  1. QUICKSTART.md        → How to run (5 min setup)"
echo "  2. MODERNIZATION.md     → Detailed upgrade info"
echo "  3. CHANGES_SUMMARY.md   → Executive summary"
echo ""
echo "🚀 QUICK START:"
echo ""
echo "   # Terminal 1: Start blockchain"
echo "   npm run hardhat:node"
echo ""
echo "   # Terminal 2: Start frontend"
echo "   npm run app:dev"
echo ""
echo "   Then open: http://localhost:3000"
echo ""
echo "📋 OR RUN EVERYTHING AT ONCE:"
echo ""
echo "   npm run dev"
echo ""
echo "========================================"
echo "✅ STACK: Hardhat + Next.js + Ethers.js"
echo "✅ SOLIDITY: 0.8.19 (Modern & Safe)"
echo "✅ STATUS: Ready to Build"
echo "========================================"
